CREATE DATABASE IF NOT EXISTS syncdb;
USE syncdb;

CREATE TABLE IF NOT EXISTS users (
    ID INT PRIMARY KEY,
    NAME VARCHAR(100),
    EMAIL VARCHAR(100),
    LAST_UPDATED_AT TIMESTAMP
        DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP
    LAST_UPDATED_BY ENUM('sheet', 'db')
);